Theodo\RogerCmsBundle\Entity\Role:
    type: entity
    table: roger_cms_role
    repositoryClass: Theodo\RogerCmsBundle\Repository\RoleRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
            nullable: false
        created_at:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated_at:
            type: datetime
            gedmo:
                timestampable:
                    on: update
