_roger_cms_admin:
    resource: "@TheodoRogerCmsBundle/Resources/config/routing/admin.yml"
    prefix: /admin

_roger_cms_frontend:
    resource: "@TheodoRogerCmsBundle/Reosurces/config/routing/frontend.yml"
