<?php

namespace Theodo\ThothCmsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LayoutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LayoutRepository extends EntityRepository
{
}