<?php

namespace Theodo\ThothCmsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LayoutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemplateRepository extends EntityRepository
{

    /**
     * List main pages
     *
     * @return array
     * @author Vincent Guillon <vincentg@theodo.fr>
     * @since 2011-06-20
     */
    public function queryByName($template_name)
    {
        // Create sql query
        $sql_query = <<<EOF
SELECT p TheodoThothCmsBundle:Page p
  WHERE p.name IS NULL
  ORDER BY p.name
EOF;

        // Create doctrine query
        $query = $this->getEntityManager()->createQuery($sql_query);

        return $query;
    }
    
    public function getSourceByName($template_name)
    {
        
    }
}