<?php

namespace Theodo\RogerCmsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleRepository extends EntityRepository
{
    const ROLE_DESIGNER        = 'ROLE_DESIGNER';
    const ROLE_ADMIN           = 'ROLE_ADMIN';
    const ROLE_CONTENT_MANAGER = 'ROLE_CONTENT_MANAGER';
    const ROLE_VISITOR         = 'ROLE_VISITOR';

    static $role_names = array(
        self::ROLE_DESIGNER        => 'Designer',
        self::ROLE_ADMIN           => 'Administrator',
        self::ROLE_CONTENT_MANAGER => 'Content Manager',
        self::ROLE_VISITOR         => 'Visitor',
    );

    /**
     * Return available roles
     *
     * @return array
     * @author Vincent Guillon <vincentg@theodo.fr>
     * @since 2011-06-24
     */
    public static function getAvailableRoles()
    {
        return self::$role_names;
    }
}