<?php

namespace Sadiant\CmsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends EntityRepository
{
    // Homepage slug
    const SLUG_HOMEPAGE   = 'homepage';
    
    // Page status
    const STATUS_DRAFT    = 'Draft';
    const STATUS_REVIEWED = 'Reviewed';
    const STATUS_PUBLISH  = 'Published';
    const STATUS_HIDDEN   = 'Hidden';

    // List of available status
    protected $availableStatus = array(
        self::STATUS_DRAFT,
        self::STATUS_REVIEWED,
        self::STATUS_PUBLISH,
        self::STATUS_HIDDEN
    );

    /**
     * Return list of available status
     *
     * @return array
     * @author Vincent Guillon <vincentg@theodo.fr>
     * @since 2011-06-20
     */
    public function getAvailableStatus()
    {
        return $this->availableStatus;
    }

    /**
     * List main pages
     *
     * @return array
     * @author Vincent Guillon <vincentg@theodo.fr>
     * @since 2011-06-20
     */
    public function queryForMainPages()
    {
        // Create sql query
        $sql_query = <<<EOF
SELECT p, c FROM SadiantCmsBundle:Page p
  LEFT JOIN p.children c
  WHERE p.parent_id IS NULL
  ORDER BY p.name
EOF;

        // Create doctrine query
        $query = $this->getEntityManager()->createQuery($sql_query);

        return $query;
    }
}