<?php

namespace Sadiant\CmsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleRepository extends EntityRepository
{
    const ROLE_USER  = 'ROLE_USER';
    const ROLE_ADMIN = 'ROLE_ADMIN';

    /**
     * Return available roles
     * 
     * @return array
     * @author Vincent Guillon <vincentg@theodo.fr>
     * @since 2011-06-24
     */
    public static function getAvailableRoles()
    {
        return array(
            self::ROLE_USER  => self::ROLE_USER,
            self::ROLE_ADMIN => self::ROLE_ADMIN,
        );
    }
}