<?php

namespace Sadiant\CmsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SnippetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SnippetRepository extends EntityRepository
{
}